### PR TITLE
2022 q1 hof

### PR DESCRIPTION
**Pull request by tomrittervg**
For review by @dveditz  and @fkiriakos07

### CODE REVIEW

**Comment by fkiriakos07** [comment]
thanks @tomrittervg do we use any date in Q1 2022 for khalid's entry to be able to include him in this PR? his report was from last year and we missed to add him then.

**Review by fkiriakos07 — APPROVED** [review]

**Comment by tomrittervg** [comment]
We could backdate it, yes. What date do you want to use? Q1 2022 (we typically use the fixed or bounty awarded date) or the reported date?

**Comment by fkiriakos07** [comment]
Not sure honestly, however would work best. The bug was fixed March 31, 2021, HoF was rewarded on April 5th, 2021.

**Comment by tomrittervg** [comment]
Okay, I changed him to 3/31

**Review by dveditz — APPROVED** [review]
r+ looks good.

Sorry for the slow response: this never showed up in my [github notifications](https://github.com/notifications?query=reason%3Areview-requested) even though my review was clearly requested here.

**Pull request merged**
