### PR TITLE
Fix a typo in MFSA 2016-89 and 90

### PR DESCRIPTION
**Pull request by kyoshino**
@albill r?

### CODE REVIEW

**Comment by albill** [comment]
r+

**Comment by kyoshino** [comment]
I'll send one more request to fix some more issues. [**glocation**](https://github.com/mozilla/foundation-security-advisories/blob/master/announce/2016/mfsa2016-89.yml#L155) is geolocation, right?

**Comment by albill** [comment]
I don't know that it is. That's taken from the title of the bug and I think it is the name of the API, not "geolocation".

**Comment by kyoshino** [comment]
Okay I'll keep it :wink:

**Pull request merged**
