### PR TITLE
 Add one late HOF entry, correct a link on another, and add one missed from 2020

### PR DESCRIPTION
**Pull request by tomrittervg**
cc @fkiriakos07

### CODE REVIEW

**Comment by fkiriakos07** [comment]
thanks @tomrittervg , we received a request from a reporter to add their linked profile too:
Name- Harsh Banshpal
Link-  https://www.linkedin.com/in/harshbanshpal/

**Review by fkiriakos07 — APPROVED** [review]

**Comment by HarshTestingAccount** [comment]
Hello Team,
My linkedin profile isn't added on the https://www.mozilla.org/en-US/security/bug-bounty/web-hall-of-fame/ hall of fame page :
Name- Harsh Banshpal
Link- https://www.linkedin.com/in/harshbanshpal/

**Comment by pmac** [comment]
Ah! The URL was added as `link:` instead of `url:` in the YAML. I'll fix it shortly.

**Comment by pmac** [comment]
Fixed in #95. Should be updated on the site within an hour or two.

**Comment by fkiriakos07** [comment]
thanks @pmac

**Pull request merged**
