### PR TITLE
Bug 1435840: Add bug bounty hall of fame files

### PR DESCRIPTION
**Pull request by pmac**
This is a work in progress, but I wanted to go ahead and get your eyes on the proposed file format. These files are the result of an extractor script I threw together to get the current data from the pages. More fields could be added to each entry as needed (like "product" mentioned in the bug) without interfering in page rendering, but name, date, and url will be the only fields that bedrock uses at first. I also added the dollar ammount from the top paragraph of each page to the data as I seem to recall that being updated from time to time as well. Let me know what you think.

### CODE REVIEW

**Comment by april** [comment]
I think `amount_paid` should just be one number, as it is shared across both bounty programs. It's just that we've updated it on the web bug bounty side, but the client side hasn't been updated.

I find `date` to be a little awkward to grok at first glance. I wouldn't mind having `year` and `quarter`, but if that's too much hassle I totally get it. Alternatively we could have those be a category and so names would only have `name` and `url` underneath them, not repeating date.

Not a big deal either way though.  :)

**Comment by albill** [comment]
I'm confused by the amount_paid entry as it is one number at the start of the file but we pay variable amounts per bounty. We often pay different amounts to each person (though there are "common" amounts so usually there are only three or four different ones most weeks). For example, depending on a client bounty bug, we've paid anywhere from $500 to $5,000 recently on a bounty so I'd like to be able to be specific per bounty award (but it be an optional field).

As a result, I would prefer "amount_paid" be an optional field associated with each bounty entry (name, date). Right now, client isn't publicly specifying the amounts but we may at a later date. Anything committed to a repo that is publicly viewable will be data that can be read by anyone so it isn't clear whether client will use this field soon as we're having discussions about when and how to disclose any amounts in public.

As to the "date" field, I want full dates per entry. We already have this in the bounty attachments in bugzilla so we should just be able to extract it (though we use a leading zero for two character months and days). It is possible that we could, for example, want to generate a monthly or six month view pages at some point. We can have Bedrock turn the dates into quarters rather than specify dates as only quarters in the file. So I do want a date on each entry, April's comments aside. :-)

**Comment by april** [comment]
`amount_paid` is the total amount paid out throughout the bug bounty's history. It's this line on the website:

> As of this date, we have paid out over **$1,600,000** across all of our bounties. Congratulations to everybody who has participated!

It's not the amount paid out on any specific bounty.

**Comment by albill** [comment]
> amount_paid is the total amount paid out throughout the bug bounty's history. It's this line on the website

Ah, ok. Well, client doesn't need that (right now).

I would like an optional field on each entry where we can specify what we paid to somone though. Chrome does that and we've debated disclosing it as well.

**Comment by april** [comment]
That would be handy. I also wouldn't mind seeing a field for the bug id number, in case we expose that someday as well.

**Comment by pmac** [comment]
Yeah. Sorry for confusion. I only added the `amount_paid` to the file as it's on both pages but different on each. Just putting it in one of the files will make it strange as the other page would need to load that data... we could have a `meta.yml` file in the repo for metadata like this that can be shared across the pages if you'd like to manage it via the repo. Otherwise it'd be pretty easy to bump that value via a bedrock PR whenever you'd like to adjust it. But we can add data other than just the list of names to these files if we need to.

**Comment by pmac** [comment]
> I find date to be a little awkward to grok at first glance. I wouldn't mind having year and quarter, but if that's too much hassle I totally get it. Alternatively we could have those be a category and so names would only have name and url underneath them, not repeating date.

Ah! That would be easier actually. I misread that in the bug then. It just says "Date of Award" as a field, so I thought that perhaps going forward you'd want to record the individual date of each award as they come in. If not then I'm absolutely happy to either have 2 fields (year and quarter) or another layer in the data for that. e.g.:

```yaml
names:
  2018-q1:
    - name: "The Dude"
      url: "https://twitter.com/thedude"
...
```

**Comment by pmac** [comment]
> As to the "date" field, I want full dates per entry. We already have this in the bounty attachments in bugzilla so we should just be able to extract it (though we use a leading zero for two character months and days). It is possible that we could, for example, want to generate a monthly or six month view pages at some point. We can have Bedrock turn the dates into quarters rather than specify dates as only quarters in the file. So I do want a date on each entry, April's comments aside. :-)

That also works for me. The preliminary file in this PR is just me putting a date at the first day of the quarter they're listed in on the page currently. We could definitely go through and update those dates to be real. If this is all in bugzilla you could also add a `bug` field and add the number(s).

**Comment by pmac** [comment]
Heh. I should read the whole thread before responding :) All of that will work fine for me. Just let me know some final thoughts and I'll get this updated.

**Comment by albill** [comment]
> Ah! That would be easier actually. I misread that in the bug then. It just says "Date of Award" as a field, so I thought that perhaps going forward you'd want to record the individual date of each award as they come in. 

Well, *I* want that. I can't speak to April. :-) 

I'd rather Bedrock look at the date entries per bounty record and make the quarters itself from them than to just break things down by quarters in this data file. That gives us more flexibility in the future.

April, I can run Raymond's script and do an initial pull of the bounty data. It would be a bit of work to add it now but it is a one time cost...

**Comment by albill** [comment]
> That would be handy. I also wouldn't mind seeing a field for the bug id number, in case we expose that someday as well.

That would be fine as well. I assume an optional field?

**Comment by pmac** [comment]
Definitely optional. At present the only info the page needs is year, quarter, and name. It will optionally use URL. All other data in the file with be ignored but available for further updates to the pages. So it's fine to have more data in the files for other purposes if you'd like.

**Comment by pmac** [comment]
And, like you said, it's easy enough for bedrock to work out year and quarter from a full date.

**Comment by pmac** [comment]
I also thought it looked like we could use something like an `organization` field for those entries that have a suffix like `Walter with Crypt0 Team` or `April - h4x0rZ`. We could standardize that a bit by making it separate, or just leave all of that in the `name` field.

**Comment by april** [comment]
@pmac, could you tell @albill that I'm fine with having the specific dates?

It was just a thought to make things a bit cleaner, but I'm fine with it if that's his preference.  :)

**Comment by albill** [comment]
> @pmac, could you tell @albill that I'm fine with having the specific dates?
Are you not talking to me now?!?!

**Comment by pmac** [comment]
Y'all are fun :) I've updated the files to remove the `amount_paid` and fix the date format that should use 2 digits for month and day as Al pointed out. If we're happy enough with this format I'll try to get the docs and linter updated to work with these new files as well.

**Comment by albill** [comment]
> If we're happy enough with this format I'll try to get the docs and linter updated to work with these new files as well.

Works for me.

**Comment by april** [comment]
Thumbs up from me as well.

**Comment by pmac** [comment]
Great 🎉 I've added linting and info about the HOF files to the README. Take one more look and I think we can merge this into master. I'll then try to get the bedrock updates done in the next few weeks.

**Comment by april** [comment]
Any chance we could update the Travis CI script such that it checks the HOF data and fails the check-in if so? I could work on that after checkin, if you'd prefer.

**Comment by albill** [comment]
> Any chance we could update the Travis CI script such that it checks the HOF data and fails the check-in if so? I could work on that after checkin, if you'd prefer.

or all data in the repo? I hand run the linter when checking in advisories because I may have broken Bedrock a few times...

**Comment by pmac** [comment]
It does do that. The travis script is set to run `python check_advisories.py --all` which will check all advisories and the HOF files (it's no longer a great name for the script, it's true). If you push directly to master there's not much that can be done, but if you file a PR it will report back to github on pass or fail. I can setup the repo so that it requires passing travis tests before commits can be pushed to master if you'd like.

**Comment by pmac** [comment]
You can see it [here](https://travis-ci.org/mozilla/foundation-security-advisories/builds/342059582) or in the box at the bottom of the PR conversation page under "Show all checks".

**Comment by albill** [comment]
This breaks my "check into master at 9 am on Firefox release day" system! :-)

I guess I could do a branch and then a PR though, as I said, I always run the linter by hand first anyway.

**Comment by pmac** [comment]
I can also intentionally break one of the HOF files so you can see a failure report if you'd like. Also Travis reports failures on IRC to `#www`. If there's a better channel for these reports just let me know.

**Comment by pmac** [comment]
@albill you running the checks manually is fine with me. Just offering options if you'd like more automated and robust checks. There's also instructions in the README for adding linting as a pre-commit git hook that will prevent a checkin if the changed files have errors.

**Comment by april** [comment]
Oh, you're totally right. I didn't realize it was rolled up as part of that and, as such, already in .travis.yml. Hooray!

**Pull request merged**
